# Site settings
title: WUXI ELEC ELECTRIC EQUIPNENT CO.,LTD
email: kim.rick@gmail.com
description: "Rick Kim's Portfolio"

# Color settings (hex-codes without the leading hash-tag)
# fed136 fec503
color:
  primary: 	118ED0 
  secondary: 00DAFF  
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/rick-kim/30/aa7/a70
  - title: github
    url: http://github.com/y7kim
  - title: envelope
    url: mailto:kim.rick@gmail.com
# phone
phone:
  - line: 0510-85022773 
  - line: 13482211596 (陆先生)
# Postal address (add as many lines as necessary)
address:
  - line: 无锡伊莱克电气有限公司
  - line: 无锡市锡北汽配城二期C幢

# Build settings
markdown: kramdown
permalink: pretty
